apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: shodan-postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
  - target:
      kind: MongoDBCommunity
      name: shodan-mongo
    patch: |-
      - op: replace
        path: /spec/statefulSet/spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 20Gi

