apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apex-forge

resources:
  - namespace.yaml
  - postgres.yaml
  - external-secret.yaml
  - db-init-job.yaml
  - maintenance-cronjob.yaml
