apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apexforge-db
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: apex-forge
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/apex-forge/db/overlays/prod
  prune: true
  wait: false
