apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shodan-db
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: shodan-monitor
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/platform/shodan-monitor/db/base
  prune: true
  wait: false
