apiVersion: v1
kind: Service
metadata:
  name: apexforge-api
  namespace: apex-forge
  labels:
    app: apexforge-api
spec:
  selector:
    app: apexforge-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
