apiVersion: v1
kind: ServiceAccount
metadata:
  name: apexforge-api
  namespace: apex-forge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apexforge-api-backup
  namespace: apex-forge
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apexforge-api-backup
  namespace: apex-forge
subjects:
  - kind: ServiceAccount
    name: apexforge-api
    namespace: apex-forge
roleRef:
  kind: Role
  name: apexforge-api-backup
  apiGroup: rbac.authorization.k8s.io
