apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apex-forge

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - deployment-api.yaml
  - apexforge-api-rbac.yaml
  - apexforge-api-service.yaml
  - apexforge-collector-service.yaml
  - external-secret.yaml
  - external-secret-virustotal.yaml
  - service-monitor.yaml
  - ingress.yaml

configMapGenerator:
  - name: apexforge-config
    literals:
      - INTERVAL_SECONDS=3600
      - LOG_LEVEL=INFO
      - VT_DAILY_BUDGET=450
      - VT_RATE_LIMIT_PER_MIN=4
      - VT_CACHE_TTL_HOURS=168
      - VT_PRIORITY_ONLY=true
      - ABUSEIPDB_DAILY_BUDGET=900
      - ABUSEIPDB_CACHE_TTL_HOURS=24
