apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shodan-db-credentials
  namespace: shodan-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: shodan-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/shodan-db-credentials
        property: DB_USER
    - secretKey: DB_PASS
      remoteRef:
        key: secret/data/shodan-db-credentials
        property: DB_PASS

