apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: shodan-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-database
  namespace: shodan-monitor
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "pods"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-database
  namespace: shodan-monitor
subjects:
  - kind: ServiceAccount
    name: mongodb-database
roleRef:
  kind: Role
  name: mongodb-database
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: shodan-mongo
  namespace: shodan-monitor
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.11"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: shodan-mongo-credentials
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: shodan-mongo-users-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
    net.bindIp: "*"
  statefulSet:
    spec:
      template:
        spec:
          serviceAccountName: mongodb-database
          securityContext:
            fsGroup: 999
            runAsUser: 999
            runAsGroup: 999
            fsGroupChangePolicy: "Always"
          nodeSelector:
            kubernetes.io/arch: amd64    # <-- Aggiunto: forza scheduling solo su nodi amd64
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "1"
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 500Mi
      volumeClaimTemplates:
        - metadata:
          name: data-volume
      spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: longhorn
          resources:
            requests:
              storage: 20Gi