apiVersion: v1
kind: Service
metadata:
  name: apexforge-collector
  namespace: shodan-monitor
spec:
  selector:
    app: apexforge-collector
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP