apiVersion: apps/v1
kind: Deployment
metadata:
  name: shodan-intel-sentinel
  namespace: shodan-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shodan-intel-sentinel
  template:
    metadata:
      labels:
        app: shodan-intel-sentinel
    spec:
      initContainers:
        - name: wait-for-dbs
          image: busybox:1.28
          command:
            - /bin/sh
            - -c
            - |
              until nslookup shodan-postgres; do echo "waiting for postgres..."; sleep 2; done
              until nslookup shodan-mongo-svc; do echo "waiting for mongo..."; sleep 2; done
      containers:
        - name: shodan-intel-sentinel
          image: ghcr.io/marmila/shodan-intel-sentinel:2.0.1
          resources:
            limits:
              cpu: "250m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: SHODAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shodan-secret
                  key: SHODAN_API_KEY

            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: shodan-mongo-credentials
                  key: MONGO_PASS

            - name: MONGO_URL
              value: "mongodb://admin:$(MONGO_PASS)@shodan-mongo-svc.shodan-monitor.svc.cluster.local:27017/shodan_intel?authSource=admin&authMechanism=SCRAM-SHA-256"

            - name: DB_HOST
              value: "shodan-postgres"
            - name: DB_NAME
              value: "shodan"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shodan-db-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: shodan-db-credentials
                  key: DB_PASS

            - name: PYTHONPATH
              value: "/app"
          envFrom:
            - configMapRef:
                name: shodan-config
          volumeMounts:
            - name: profiles-volume
              mountPath: /app/profiles.yaml
              subPath: profiles.yaml
      volumes:
        - name: profiles-volume
          configMap:
            name: shodan-profiles


