apiVersion: apps/v1
kind: Deployment
metadata:
  name: shodan-worker
  namespace: shodan-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shodan-worker
  template:
    metadata:
      labels:
        app: shodan-worker
    spec:
      containers:
        - name: shodan-worker
          image: ghcr.io/marmila/shodan-sec-monitor:v1.2.3
          imagePullPolicy: IfNotPresent
          env:
            - name: SHODAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: shodan-secret
                  key: SHODAN_API_KEY
            - name: TARGETS
              valueFrom:
                configMapKeyRef:
                  name: shodan-config
                  key: TARGETS
            - name: DB_HOST
              value: shodan-postgres.shodan-monitor.svc.cluster.local
            - name: DB_NAME
              value: shodan
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: shodan-db-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: shodan-db-credentials
                  key: DB_PASS
            - name: INTERVAL_SECONDS
              value: "21600"
            - name: REQUEST_DELAY
              value: "1.0"
