apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shodan-api
  namespace: shodan-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: shodan-secret
    creationPolicy: Owner
  data:
    - secretKey: SHODAN_API_KEY
      remoteRef:
        key: secret/data/shodan
        property: api_key

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: abuseipdb-api
  namespace: shodan-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: abuseipdb-secret
    creationPolicy: Owner
  data:
    - secretKey: ABUSEIPDB_API_KEY
      remoteRef:
        key: secret/data/abuseipdb
        property: api_key
