apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openai-api
  namespace: shodan-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: openai-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: secret/data/openai
        property: api_key
