apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: virustotal-api
  namespace: shodan-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: virustotal-secret
    creationPolicy: Owner
  data:
    - secretKey: VIRUSTOTAL_API_KEY
      remoteRef:
        key: secret/data/virustotal
        property: api_key