apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shodan-api
  namespace: shodan-monitor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: shodan-secret
    creationPolicy: Owner
  data:
    - secretKey: SHODAN_API_KEY
      remoteRef:
        key: secret/data/shodan
        property: api_key
