apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shodan-monitor

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - external-secret.yaml

configMapGenerator:
  - name: shodan-config
    literals:
      - INTERVAL_SECONDS=21600
      - REQUEST_DELAY=1.0


