apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shodan-monitor

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - external-secret.yaml
  - external-secret-virustotal.yaml
  - service-monitor.yaml
  - apexforge-collector-service.yaml

configMapGenerator:
  - name: shodan-config
    literals:
      - INTERVAL_SECONDS=3600
      - LOG_LEVEL=INFO



