apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shodan-monitor

resources:
  - namespace.yaml
  - postgres.yaml
  - cronjob.yaml
  - configmap.yaml
  - external-secret.yaml

components: []

configMapGenerator:
  - name: shodan-monitor-values
    behavior: merge
    files:
      - values.yaml

