apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apexforge-metrics
  namespace: shodan-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: apexforge-collector
  endpoints:
    - port: "8000"
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http